version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - AI_PROVIDER=huggingface
      - HUGGINGFACE_API_KEY=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
      - HUGGINGFACE_MODEL_ID=Qwen/Qwen2.5-Coder-32B-Instruct
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge